#CONFIG_ZMK_POINTING=y
#CONFIG_ZMK_SPLIT=y
#CONFIG_ZMK_STUDIO=y
#CONFIG_ZMK_BOARD_COMPAT=y
#CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering idle state
#CONFIG_ZMK_IDLE_TIMEOUT=30000
# Milliseconds of inactivity before entering deep sleep
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
